# Railway configuration to force Python detection
# This file tells Railway to use Python instead of Node.js/Bun

# Python requirements
python-version: 3.11

# Build command
build: pip install -r requirements.txt

# Start commands for each service
start:
  reply-bot: python main.py
  cron: python cron.py
